# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redex}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Hickman"]
  s.date = %q{2011-03-03}
  s.description = %q{TODO: longer description of your gem}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/redex.rb",
    "lib/redex/Document.rb",
    "lib/redex/configuration.rb",
    "lib/redex/content_type.rb",
    "lib/redex/dictionary.rb",
    "lib/redex/dictionary_item.rb",
    "lib/redex/document_content.rb",
    "lib/redex/document_section.rb",
    "lib/redex/document_type.rb",
    "lib/redex/helper.rb",
    "lib/redex/helper/data.rb",
    "lib/redex/helper/document_util.rb",
    "lib/redex/helper/file_util.rb",
    "lib/redex/helper/type.rb",
    "lib/redex/line.rb",
    "lib/redex/match.rb",
    "lib/redex/parser.rb",
    "lib/redex/section_type.rb",
    "spec/data/mock_web_page.html",
    "spec/data/mock_xml_doc.xml",
    "spec/dictionary_files/cast.txt",
    "spec/dictionary_files/two.txt",
    "spec/redex/configuration_spec.rb",
    "spec/redex/content_type_spec.rb",
    "spec/redex/dictionary_item_spec.rb",
    "spec/redex/dictionary_spec.rb",
    "spec/redex/document_content_spec.rb",
    "spec/redex/document_section_spec.rb",
    "spec/redex/document_spec.rb",
    "spec/redex/document_type_spec.rb",
    "spec/redex/file_helper_spec.rb",
    "spec/redex/line_spec.rb",
    "spec/redex/match_spec.rb",
    "spec/redex/parser_spec.rb",
    "spec/redex/runner_spec.rb",
    "spec/redex/section_type_spec.rb",
    "spec/redex_spec.rb",
    "spec/sample_files/chemist.txt",
    "spec/sample_files/engineer.txt",
    "spec/sample_files/engineer2.txt",
    "spec/sample_files/history_professor.txt",
    "spec/sample_files/hostess.txt",
    "spec/sample_files/law_professor.txt",
    "spec/sample_files/lawyer.txt",
    "spec/sample_files/lawyer2.txt",
    "spec/sample_files/lawyer3.txt",
    "spec/sample_files/lawyer5.txt",
    "spec/sample_files/lawyer6.txt",
    "spec/sample_files/lawyer7.txt",
    "spec/sample_files/librarian.txt",
    "spec/sample_files/researcher.txt",
    "spec/sample_files/teacher.txt",
    "spec/sample_files/therapist.txt",
    "spec/spec_helper.rb",
    "spec/test_files/episodes.txt",
    "spec/test_files/test.txt",
    "spec/test_files/test2.txt"
  ]
  s.homepage = %q{http://github.com/mhickman84/redex}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/redex/configuration_spec.rb",
    "spec/redex/content_type_spec.rb",
    "spec/redex/dictionary_item_spec.rb",
    "spec/redex/dictionary_spec.rb",
    "spec/redex/document_content_spec.rb",
    "spec/redex/document_section_spec.rb",
    "spec/redex/document_spec.rb",
    "spec/redex/document_type_spec.rb",
    "spec/redex/file_helper_spec.rb",
    "spec/redex/line_spec.rb",
    "spec/redex/match_spec.rb",
    "spec/redex/parser_spec.rb",
    "spec/redex/runner_spec.rb",
    "spec/redex/section_type_spec.rb",
    "spec/redex_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.4"])
      s.add_runtime_dependency(%q<redis-namespace>, ["~> 0.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
      s.add_dependency(%q<redis-namespace>, ["~> 0.1"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
    s.add_dependency(%q<redis-namespace>, ["~> 0.1"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

